services:
  postgresql:
    image: postgres:16
    container_name: postgresql
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=database
      - POSTGRES_PASSWORD=TtHcwIuW82
      - POSTGRES_USER=admin
    ports:
      - 5435:5432
    networks:
      - backend

  healthy-smile-backend:
    depends_on:
      - postgresql
    image: nick552/healthy-smile:latest
    container_name: healthy-smile-backend
    ports:
      - "80:8080"
    environment:
      - BASE_URL=https://nick552.ardyc.ru
      - DB_URL=jdbc:postgresql://postgresql:5432/database
      - DB_USERNAME=admin
      - DB_PASSWORD=TtHcwIuW82
      - JWT_SECRET_KEY=eLkWd0dbipqagu9nRinYXO5Vyc0XiOXebhSdH0ibkuE=
      - HEALTHY_SMILE_EMAIL=TTchip552@ya.ru
      - EMAIL_SECRET_KEY=vrypnxievxmrmisy
    networks:
      - backend

#  liquibase-migrations:
#    image: liquibase/liquibase:4.25
#    depends_on:
#      - postgresql
#    container_name: liquibase
#    command:
#      - --changelog-file=master.xml
#      - --driver=org.postgresql.Driver
#      - --url=jdbc:postgresql://postgresql:5432/database
#      - --username=postgres
#      - --password=postgres
#      - update
#    volumes:
#      - ./migrations:/liquibase/changelog
#    networks:
#      - backend


networks:
  backend: { }

volumes:
  postgres: { }
